// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRiuAVUemZzij2SgURUSnMDw_dZ6lK180',
    appId: '1:9398436884:web:f71390abd7f2d4ebe11301',
    messagingSenderId: '9398436884',
    projectId: 'ihitstasks',
    authDomain: 'ihitstasks.firebaseapp.com',
    storageBucket: 'ihitstasks.appspot.com',
    measurementId: 'G-ZBZDS840RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJCpPh0xW1Shldsh1-Nu92fV3JqUhVw8s',
    appId: '1:9398436884:android:d72522d95d6719f3e11301',
    messagingSenderId: '9398436884',
    projectId: 'ihitstasks',
    storageBucket: 'ihitstasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVuOYJfAPFty8sj7-b6Mxe2fJySlIDls',
    appId: '1:9398436884:ios:5ddf205e0a99aee8e11301',
    messagingSenderId: '9398436884',
    projectId: 'ihitstasks',
    storageBucket: 'ihitstasks.appspot.com',
    iosBundleId: 'com.example.tms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVuOYJfAPFty8sj7-b6Mxe2fJySlIDls',
    appId: '1:9398436884:ios:4d8d6d91dcae5963e11301',
    messagingSenderId: '9398436884',
    projectId: 'ihitstasks',
    storageBucket: 'ihitstasks.appspot.com',
    iosBundleId: 'com.example.tms.RunnerTests',
  );
}
